### ISSUE TITLE
Deployment Scripts

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#10]
- [ ] Horizontally scalable deployment using Ansible on a GPU based inventory

Karun

**Comment by KarunAgarwal** [comment]
**Problem Statement:**

We have X no. of models each with different kinds of requirements in terms of GPU. We have Y no. of machines with details about their configurations. We need to build a matching algorithm that dynamically deploys the model in a group of machines. 

End Requirements:

1. A layer that handler routing of requests to the respective group of machines based on model
2. A layer that load balances requests among the respective group of machines

**Other Problems that we might had to tackle:**

1. How will the redeployment of a given model happen?
2. What if we introduce a new model, how will it be mapped and deployed?

**Future Scopes:**

1. How to package the models

**Comment by singhalkarun** [comment]
As per research around the problem statement, k8s seems to be the way to go.

A. Infrastructure Level

1. On Cloud -> Managed Kubernetes Cluster e.g., AWS EKS 

2. On Premises -> https://github.com/rancher/rancher     
      
B. MLOps/DevOps

1. On Cloud -> Managed services like AWS Sagemaker
        
2. On Premises -> https://github.com/devtron-labs/devtron

Challenges:
https://www.arrikto.com/blog/gpu-virtualization-in-k8s-challenges-and-state-of-the-art/

**Comment by ChakshuGautam** [comment]
For first deployment we might not be k8s ready.

**Comment by singhalkarun** [comment]
Steps we should take:

1. Distribute AI Tools into multiple smaller components that can be independently functional

**Comment by singhalkarun** [comment]
@ChakshuGautam @suresh12 

Plan:

- [ ] Use terraform to provision virtual machines on Azure
- [ ] Configure dynamic inventory in Ansible using [Ansible dynamic inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html)
- [ ] Group ansible invetory into swarm manager and worker nodes on the basis of tags
- [ ] Write ansible playbook to automatically initialize manager on vm's in manager group and add the vm's in worker group as worker to swarm manager
- [ ] Finally use ansible playbook to start instances of ai-tools utilzing the manager node

Note: 

For now, we'll rely on docker swarm internal load balancing, refer https://docs.docker.com/engine/swarm/key-concepts/#load-balancing

**Comment by singhalkarun** [comment]
Deployment is done with docker swarm (1 manager node and 2 worker node - Using non-gpu instances as we don't have gpu quota available in azure) - http://52.172.248.16/

Things left to be done:-

- [ ] Update ansible files to download akai.csv file and bind with running containers
- [ ] Figure out a way to configure let's encrypt with docker swarm to enable https

**Comment by singhalkarun** [comment]
> @ChakshuGautam @suresh12
> 
> Plan:
> 
> * [x]  Create a bastion that has access to azure
> * [x]  Use terraform to provision virtual machines on Azure
> * [x]  Configure dynamic inventory in Ansible using [Ansible dynamic inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html)
> * [x]  Group ansible invetory into swarm manager and worker nodes on the basis of tags
> * [x]  Write ansible playbook to automatically initialize manager on vm's in manager group and add the vm's in worker group as worker to swarm manager
> * [x]  Finally use ansible playbook to start instances of ai-tools utilzing the manager node
> 
> Note:
> 
> For now, we'll rely on docker swarm internal load balancing, refer https://docs.docker.com/engine/swarm/key-concepts/#load-balancing

Deployment is done with docker swarm (1 manager node and 2 worker node - Using non-gpu instances as we don't have gpu quota available in azure) - http://52.172.248.16/

Things left to be done:-

- [ ] Update ansible files to download akai.csv file and bind with running containers
- [ ] Figure out a way to configure let's encrypt with docker swarm to enable https

**Comment by singhalkarun** [comment]
Closing this as implemented.
