### ISSUE TITLE
Odia Dictionary- extracted the relevant data from an Odia dictionary (Odia-English word pairs)

### ISSUE THREAD

**Issue by shrivastava95** [Samagra-Development/ai-tools#106]
[Odia Dictionary.pdf](https://github.com/Samagra-Development/ai-tools/files/11561548/Odia.Dictionary.pdf)
We want to create a parser that parses this to a Dataset.

_Originally posted by @ChakshuGautam in https://github.com/Samagra-Development/ai-tools/issues/97#issuecomment-1562321681_

---

I have currently found an online OCR tool which parses images and produces high quality odia+english text.  - https://oriya.indiatyping.com/index.php/apps/ocr-odia

Is there some way to automate the dictionary parsing using this? I am currently using selenium to feed the pdf pages to the tool linked above, but the formatting of the OCR output is a big problem and I do not know how to work around that without using GPT-4 to tabulate the raw data (I do not have access to gpt4 aside from the 20 free API calls provided by https://www.perplexity.ai/ , and chatgpt fails to do it properly)

**Contributors, please feel free to carry the torch on from here and finish the Odia to English Dataset / dictionary creation task, as this will be an integral part of the Dictionary Augmentation task!**

*Resources*
1. Zip file containing the pages of the PDF file converted to a high quality image format - https://drive.google.com/file/d/1OrvSPi6bnIBIDM6M7-JwYfHExu3SWhHU/view?usp=sharing
2. https://selenium-python.readthedocs.io/installation.html
3. Sample prompt input given to GPT4 (perplexity.ai) - [unformatted-output-gpt4-prompt.txt](https://github.com/Samagra-Development/ai-tools/files/11571196/unformatted-output-gpt4-prompt.txt)
4. Sample prompt output showing acceptably parsed dictionary information - [gpt4-formatted-output.txt](https://github.com/Samagra-Development/ai-tools/files/11571193/gpt4-formatted-output.txt)

Anyone with access to GPT4 may parse the PDF in this manner. I do not have access hence posting this issue for others to carry forward with alternates.

**Comment by shrivastava95** [comment]
I have completed parsing the dictionary into a very unclean csv file - [parsed_dict_very_unclean.csv](https://github.com/Samagra-Development/ai-tools/files/11580906/parsed_dict_very_unclean.csv)

Other contributors may try to begin the process of cleaning this file through any manual or automated methods.

**FOR ANYONE INTERESTED IN IMPROVING THE EXTRACTION PIPELINE (from original PDF images to CSV)**
Code files used (in order of the code flow) - [FINAL.zip](https://github.com/Samagra-Development/ai-tools/files/11580929/FINAL.zip)
1. pdfmaker.py - uses **Tesseract** to read images and convert them to pdfs
2. reader.py - converts pdfs to text files containing the raw OCR output
3. sender.py - uses **ChatGPT API** to reorganised and parse the OCR outputs
4. preprocess.py - some preprocessing before collecting the ChatGPT outputs
5. maker.py - makes csv file from the texts

**Comment by xorsuyash** [comment]
If we look at the parsed data we have  , in the odia words column we have some additional english tags with odia words , and some columns are flipped to english columns and some more noise . We can prepare the script to remove all these and then we can feed it to gpt  to clean it much further and result the data in desired format .
Working on it

**Comment by ChakshuGautam** [comment]
@xorsuyash thanks for joining the community. [shrivastava95](https://github.com/shrivastava95) will push the code in a repo where we can collaborate on the approach you shared. Would love for this to be resolved as quickly as possible.

**Comment by shrivastava95** [comment]
I have edited the original Issue message to include a link to the github repo. Please review. @xorsuyash 
I will edit the readme file explaining how to use the code, and add all the necessary issues from our discussions. @ChakshuGautam

**Comment by shrivastava95** [comment]
Another idea for solving the cleaning problem atleast partially - using `--psm 6` instead of `--psm 3` with Tesseract tends to result in parsed OCR output which mutually cover the mistakes of each other. 

Maybe we can prompt engineer GPT to parse these two jointly into one table while removing the non-common errors of each other and keeping the correct bits.

Below I have attached two OCR outputs which contributors can use for testing the prompt engineering.
[psm3.txt](https://github.com/Samagra-Development/ai-tools/files/11581384/1.txt)
[psm6.txt](https://github.com/Samagra-Development/ai-tools/files/11581385/2.txt)

**Comment by xorsuyash** [comment]
Followed by @shrivastava95  idea merging the files from psm3 and psm6 we can promt engineer gpt to verify that all the words are correctly mapped too their translation or not .

If the translations are not correctly mapped then we can replace them with their correct translation .
below i have attached two files which will the first is output after merging psm3.txt and psm6.txt and then second is output after verifying the correct mapping .


[test_output.txt](https://github.com/Samagra-Development/ai-tools/files/11581651/test_output.txt)
[final_ouput.txt](https://github.com/Samagra-Development/ai-tools/files/11581652/final_ouput.txt)

**Comment by shrivastava95** [comment]
Merged `--psm 3` and `--psm6` with [odia-dictionary/mergegpt](https://github.com/shrivastava95/odia-dictionary/mergegpt)

Find the cleaner version of the parsed dictionary here - [odia-dictionary/mergegpt/parsed_dicts_merged/parsed_dict_merged_unclean.csv](https://github.com/shrivastava95/odia-dictionary/mergegpt/parsed_dicts_merged/parsed_dict_merged_unclean.csv)

Suggested to continue any cleaning work on this new csv file as it has less errors.

**Comment by GautamR-Samagra** [comment]
@shrivastava95  can you link the work done here to the tickets created today?
