### ISSUE TITLE
Chunking to PDFs

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#109]
Documenting the pdfs that need to be chunked now- 
https://drive.google.com/drive/u/0/folders/1sAsuh-EFH-xmFYrxzhmj0VRUZYNzsyLw

**Comment by inkerton** [comment]
chunks based on topics and you want to save it in which format???

**Comment by GautamR-Samagra** [comment]
> chunks based on topics and you want to save it in which format???

You can store in any format. Even inside a csv is fine for now. Later on, they;ll be inserted into a vector DB after getting their embeddings
