### ISSUE TITLE
Parallel Execution of Processes on the Same Port Causing Port Conflict

### ISSUE THREAD

**Issue by ysrastogi** [Samagra-Development/ai-tools#113]
I encountered an issue while running the following command from **deploy.sh:**

_**cd ./src/text_translation/ai4bharat & sh deploy.sh & cd .. & cd ..**_

This command initiates the parallel execution of multiple processes on the same port, resulting in a port conflict. Due to this conflict, the desired functionality cannot be achieved as expected.

To reproduce the issue:

1. Run the above command in the specified directory.
2. Observe the port conflict error message.

Expected Behavior:
The processes should be executed sequentially or in a manner that avoids port conflicts, ensuring that each process is allocated a unique port.
![Screenshot from 2023-05-31 19-16-14](https://github.com/Samagra-Development/ai-tools/assets/97824759/6aa95e0d-55b2-4b2b-a3e3-a9378b89c456)

**Comment by ysrastogi** [comment]
Please assign this issue to me. I would like to work on it.

**Comment by singhalkarun** [comment]
Hey @ysrastogi we are already in process in implementing a different flow for deployment of services, you can checkout the ongoing work at https://github.com/Samagra-Development/ai-tools/tree/restructure
