### ISSUE TITLE
Generic HF Interface Use Case

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#114]
API to be similar to [this](https://github.com/stanfordnlp/dsp/blob/298fac8937fdf7326d1b85546ecd41f099ed33e2/intro.ipynb#L2226).

**Comment by GautamR-Samagra** [comment]
Covered in https://github.com/Samagra-Development/ai-tools/issues/42 and https://github.com/Samagra-Development/ai-tools/issues/78
