### ISSUE TITLE
Add table of dictionary of Odia and English words to augment translation

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#119]
Add a  table of DB with the following columns : 
- index 
- odia word
- Correct_translation

**Comment by Harsh-1309** [comment]
Hi @GautamR-Samagra, I'd like to work on this. Can you provide a bit more details on what needs to be done?

**Comment by ysrastogi** [comment]
@GautamR-Samagra I would like to work on this issue. Please provide me more details.

**Comment by GautamR-Samagra** [comment]
Sorry, this was completed by Amruth in another ticket.
