### ISSUE TITLE
Github Workflow to build and push docker image of each model separately to Github Packages

### ISSUE THREAD

**Issue by singhalkarun** [Samagra-Development/ai-tools#120]

**Comment by Manas23601** [comment]
I can work on this. Can you give me the requred credential?

**Comment by singhalkarun** [comment]
Hey @Manas23601, can you share a screenshot of published packages so as to verify if this workflow is working fine. Also, I am expecting the workflow to dynamically generate docker-compose using generate.sh and then push the images to Github Packages.
