### ISSUE TITLE
Create Embeddings API

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#14]
@GautamR-Samagra 

### Step 1
- [x] #17
- [ ] #18

### Step 2
- [ ] #19
- [ ] #20
- [ ] #21

### Step 3
- [ ] Refactoring
- [x] #22

**Comment by GautamR-Samagra** [comment]
Currently takes csv as input and outputs a csv with column having the embeddings. Vector DB can be incorporated later

**Comment by sanjay-aurigait** [comment]
will work on first step upload csv
