### ISSUE TITLE
Checking relevancy of content to question asked 

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#146]
Mini block -  being able to confirm that a certain content is relevant to the question asked. 

Testing out [Roberta_Squad](https://huggingface.co/deepset/roberta-base-squad2) for checking if a content piece is relevant to the question being asked. 
While the above model works well with questions and answers, our information is not usually structured in that format. We usually have a user asking questions (in the field of agriculture) and we have content pieces that may or may not be relevant to it.  
We need to create setup to test out accuracy of Roberta of being able to detect that some content is not relevant to a question

**Comment by Gautam-Rajeev** [comment]
https://github.com/explodinggradients/ragas/tree/main
