### ISSUE TITLE
Agent to search for new content on web

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#148]
## Description
Build an agent that is capable of searching for new content on the web and supplementing GPT with context when content is not available.

## Goals
- [ ] Develop an agent that can search the web for new content based on specified criteria
- [ ] Implement a mechanism to supplement GPT with context from the newly found content
- [ ] Enhance GPT's ability to provide relevant and up-to-date information using the agent's search results

## Expected Outcome
By building an agent for searching new web content, you can ensure that GPT is supplemented with context even when the required information is not available within its existing knowledge base. This improves the system's ability to provide accurate and up-to-date responses to user queries.

## Acceptance Criteria
- [ ] The agent is developed to search the web for new content based on specified criteria
- [ ] Mechanisms are implemented to extract and integrate context from the search results into GPT
- [ ] GPT's responses are enhanced with relevant and up-to-date information using the agent's search results

## Implementation Details
[List any technical details about the proposed implementation, including any specific technologies that will be used.]

## Mockups / Wireframes
[N/A]

---

### Project
AI-tools

### Product Name:
Amakrush AI

### Organization Name:
Samagra

### Domain
Social Welfare

### Tech Skills Needed:
Web scraping, Natural Language Processing

### Mentor(s)
@ChakshuGautam

### Complexity
High

### Category
Machine Learning

### Sub Category
Knowledge Enhancement

**Comment by GautamR-Samagra** [comment]
An ideal solution includes a fact checking mechanism to it built along the lines of [this](https://www.microsoft.com/en-us/research/group/deep-learning-group/articles/check-your-facts-and-try-again-improving-large-language-models-with-external-knowledge-and-automated-feedback/)

**Comment by Maatrika-P** [comment]
Can you provide some more description, so i can help you more efficiently!

**Comment by inkerton** [comment]
Please assign it to me as I am currently working on it.

**Comment by KavyaSethia** [comment]
@Shruti3004 @GautamR-Samagra I would like to contribute to the project.
