### ISSUE TITLE
Implement circuit breaker to a different model if one fails

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#15]
[Sample implementation library](https://github.com/fabfuel/circuitbreaker)

Alternatives
1. [This](https://github.com/dream11/kong-circuit-breaker) when the models are deployed over [Kong](https://konghq.com/). [Blog here](https://blog.dream11engineering.com/break-circuits-save-kong-3680d88a0639).
2. [Add Rate Limiter](https://github.com/dream11/kong-scalable-rate-limiter) when using with Kong.

**Comment by eternal-f1ame** [comment]
Can you assign me this issue, please?

**Comment by Jiya126** [comment]
@ChakshuGautam What model do we need to set as alternate model if the primary one fails

**Comment by ChakshuGautam** [comment]
Hey @Jiya126 look at [Hystrix](https://github.com/Netflix/Hystrix). It allows you to configure fallbacks. Whoever is using ai-tools should be allowed to configure fallbacks.

**Comment by GautamR-Samagra** [comment]
@ChakshuGautam do close this if completed
