### ISSUE TITLE
Gitpod for AI tools

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#153]
## Description
Setup Gitpod for faster contributions.

## Goals
- [ ] Be able to collate all required libraries for current setup to work from scratch 
- [ ] Setup Gitpod for ai-tools repo
- [ ] Make Gitpod accessible from button click on main tab (readme)

## Expected Outcome
lets anyone access a virtual machine with a pre-configured development environment directly from their browser. By leveraging Gitpod's cloud-based infrastructure, developers can easily set up and share reproducible coding environments with others.
After setting up the .gitpod.yml file, whenever someone clicks on the "Gitpod" button on the repository's page, a new Gitpod workspace will be created based on the defined configuration. Users can then access this workspace through their browser and start coding immediately.

## Acceptance Criteria
- [ ] PR with Gitpod button on README file of the repo
- [ ] Working Gitpod instance with all models accessible through API
- [ ] No file to be created in gitpod instance except any required .env files

## Implementation Details
[List any technical details about the proposed implementation, including any specific technologies that will be used.]

## Mockups / Wireframes
[BBF](https://gitpod.io/#https://github.com/AmakrushAI/bff)

---

### Project
[AI-tools]

### Organization Name:
[Samagra]

### Domain
[Social Welfare ]

### Tech Skills Needed:
[Gitpod]

### Mentor(s)
[@ChakshuGautam]

### Complexity
[Medium]

### Category
[CI/CD]

### Sub Category
[Configuration][Beginner friendly]

**Comment by Manas23601** [comment]
I would like to give this issue a shot

**Comment by GautamR-Samagra** [comment]
Some work on it has been done here - https://github.com/Samagra-Development/ai-tools/issues/59
However, Gitpod setup doesn't work right now. Needs to fix Python version
