### ISSUE TITLE
Add health check API

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#155]
## Description
Add a global `/health` endpoint that allows checking the health of each model and any external dependent services.

## Goals
- [ ] Implement a `/health` endpoint in the application
- [ ] Configure the `/health` endpoint to check the health of each model
- [ ] Integrate external health checks using https://yaus.xyz/health for any dependent services
- [ ] Update `generate.sh` to include health checks in the generated Docker Compose and Nginx configuration files

## Expected Outcome
The `/health` endpoint will provide a centralized way to monitor the health of each model in the application. By accessing this endpoint, users can check the status and availability of all models and any external services used by the application.

## Acceptance Criteria
- [ ] The `/health` endpoint is accessible and returns a JSON response indicating the health status of each model and external dependencies
- [ ] The health checks for each model are implemented and return the appropriate status
- [ ] External health checks using https://yaus.xyz/health are integrated and provide accurate information about dependent services
- [ ] The `generate.sh` script is updated to include the necessary configurations for health checks in the generated Docker Compose and Nginx files

## Mockups / Wireframes
[N/A]

---

### Project
[AI-tools]

### Product Name:
[AmakrushAI]

### Organization Name:
[Samagra]

## Tech Skills Needed:
Node.js, Express.js, Docker, Nginx

## Mentor(s)
@ChakshuGautam

## Complexity
Medium

## Category
Backend

## Sub Category
[API Development]

**Comment by chandra-pro** [comment]
Hii @GautamR-Samagra 
I am very good at backend development and I want to contribute to this issue.

**Comment by utkars3** [comment]
@GautamR-Samagra can i work on this?

**Comment by Gautam-Rajeev** [comment]
Anyone interested in the ticket can just contribute PRs. :)

**Comment by venkateshreddy2003** [comment]
Hey @GautamR-Samagra  i want to contribute as i was working as a backend developer

**Comment by jayesh9747** [comment]
hii i am new to open source , but I have good in this tech stack , so how I start to contribute ? plz guide me

**Comment by jayesh9747** [comment]
hey @GautamR-Samagra  , i am new to at open source , but I know this tech stack , I want to also contribute in this project how to start contributing this project ?

**Comment by singhalkarun** [comment]
All the models in ai-tools have curl request format in Readme file. Please take that as reference to create /health endpoint.

**Comment by singhalkarun** [comment]
All the models in ai-tools have curl request format in Readme file. Please take that as reference to create /health endpoint.

**Comment by M0hitSingh** [comment]
@GautamR-Samagra I would like to work on this issue
I see some progress has already been made, what are the things left that i can work on... could you please elaborate a bit.

**Comment by Shurtu-gal** [comment]
@GautamR-Samagra I have an ample amount of experience in backend and am up for this.
Could I work on this?

**Comment by ChakshuGautam** [comment]
@Shurtu-gal @M0hitSingh we are closing stale tickets and creating new ones today/tomorrow. Please check those out.
