### ISSUE TITLE
PDF parsing - detecting text boundary 

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#164]
### Description:
The purpose of this ticket is to develop a solution for quickly identifying text boundaries for any given PDF page. The solution should be able to automatically detect text regions, with the provision for human intervention to correct any errors in the boundary detection process. It should include a survey of existing open source tech that does this already (if any). 

It should only be able to detect free text for now. It can ignore images, charts, tables etc.  

This is only for PDFs for which libraries like [PyPDF2](https://pypi.org/project/PyPDF2) aren't useful in extracting text

**Comment by shrivastava95** [comment]
*Current progress on this:*
- Currently have a working solution for line-by-line parsing
- Working on methods to identify columns
- Working on methods to identify and order paragraphs
  - Tesseract OCR that provides bounding boxes over the desired regions of text.
  - Looking into Detectron2 for deep-learning based boundary detection
    - https://github.com/Layout-Parser/layout-parser/blob/main/installation.md
    - https://www.analyticsvidhya.com/blog/2021/05/document-layout-detection-and-ocr-with-detectron2/
- Working on a small pop-up window to display and edit the obtained bounding box regions with human input.
