### ISSUE TITLE
Create test suite for asking questions and checking if relevant content is retrieved

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#169]

**Comment by H4R5H1T-007** [comment]
Current Benchmark score by using Cosine similarity method in comparison with [standard](https://github.com/OpenNyAI/jugalbandi-api/tree/main) api for content retrieval:-
Standard API Retrieval scores :- {'map@5': 0.18, 'mrr': 0.18, 'ndcg@5': 0.3270117461231739}
Our Method Retrieval scores :- {'map@5': 0.29, 'mrr': 0.29, 'ndcg@5': 0.42618595071429155}
[Here's the link to the Colab to reproduce results.](https://colab.research.google.com/drive/1Bg4KiNZ8pjJNm-ceb9ooiX2L0IjK-G6S?usp=sharing)
