### ISSUE TITLE
Upload CSV API - Sanjay

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#17]
Python decorator over an API Call

Input
- [ ] Streaming CSV file
- [ ] Fetch a file from a remote location

Implementation Details
- [ ] Keep it in memory
- [ ] Store it in folder /tmp on the server => Load it in memory through a CSV Reader

Output
- [ ] CSV Reader

**Comment by sanjay-aurigait** [comment]
@ChakshuGautam , I will work on this

**Comment by ArjunYaduvanshi02** [comment]
can i work on this issue? @ChakshuGautam
