### ISSUE TITLE
Implementing DSP to break down prompt to improve content retrieval

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#172]

**Comment by ksgr5566** [comment]
[DSP](https://github.com/stanfordnlp/dsp/tree/main) needs to be explored for questions that needs complex reasoning where a single fetch via RM doesn't give accurate information to LM to frame a proper response.

Todo:
- Identify when content is not enough (i.e., when not enough content is present in DB to answer the question from user).
- Identify when to go back to user for more information.
- Identify when DSP is required, i.e., if a proper response can't be framed with a simple RAG.
- Get LM history at each hop so as to better understand the reasoning.
- The original DSP approach uses GPT-3.5 as its LM, use a lighter model like GPT-2 and compare the performance.

**Comment by ksgr5566** [comment]
How DSP works in short:

- DSP works by breaking down original question into sub-questions via inbetween rationales, forming a chain of thought before finally arriving at a prediction for the original question.

For example:
```
Question: I am a Farmer living in a village can I avail this scheme?
```

Now a rationale and a search query are generated for this question:

```
Rationale: Let's think step by step. To answer this question, we first need to find out if there is a scheme available for farmers in villages.
Search Query: Are there any government schemes available for farmers in villages?
```

Via RM relevant context is retreived based on the search query. Based on the context, one more rationale is generated which helps form another search query.
```
Rationale: Let's think step by step. Based on the context, we have learned the following. - The scheme mentioned is the Pradhan Mantri Awas Yojana (Urban) [PMAY(U)]. - The scheme is for providing benefits of owning a pucca house to eligible beneficiaries. - The beneficiary family should not own a pucca house in their name or in the name of any member of their family. - The scheme has income eligibility criteria.
Search Query: What are the eligibility criteria for farmers to avail the Pradhan Mantri Awas Yojana (Urban) [PMAY(U)] scheme?
``` 

Again the process repeats. Context is retrieved for the search query. A rationale is generated and this time a final conclusion is produced. 
```
Rationale: Let's think step by step. [2] states that a beneficiary family should not own a pucca house in any part of India. However, it also mentions that a person with a pucca house with a built-up area less than 21 sq.m may be included for enhancement of existing dwelling units up to 30 sq.m. Therefore, if the farmer does not own a pucca house or if their existing house meets the criteria for enhancement, they may be eligible for the scheme.
Answer: Yes, a farmer living in a village can avail the Pradhan Mantri Awas Yojana (PMAY) if they do not own a pucca house or if their existing house meets the criteria for enhancement.
```

For the above process to work better, few train samples need to be provided. Its hard to have labeled data with rationales and search queries. So the Demonstrate part of the DSP takes care of this. It automatically generates demonstrations and uses the specific sample if the final conclusion arrived at matches with the true answer, else ignores it. How this is implementated for long passage answers can be referred to [here](https://github.com/stanfordnlp/dspy/issues/82#issuecomment-1675923802).

Few problems observed with DSP are as follows:
- We are passing in demonstrations of multiple train samples for answering a single question, this involves passing in context retrieved for demos, which increase as we retrieve more passages from RM. For the above example, using 4 training samples, in a 2 hop setting (i.e., 2 inbetween subqueries are generated before finally reaching a conclusion), and using k=3 for retrieval, an average of 11-12k tokens are sent to each GPT-3.5 call. So if we increase the k value, the tokens used will blow up. One possible solution, is to not pass in the entire context or append retreived context every hop but summarize the context and use that summary instead.
- Using low level LLMs like GPT-2 or bart do not seem to work as they do not seem to understand long content, and just repeat themselves. An example with GPT-2 is as follows:
```
Answer questions with concise answers without redundant information.

---

Follow the following format.

Question: ${the question to be answered}
Answer: ${a crisp and concise answer without redundant information}

---

Question: Can I get support to buy land to build house?
Answer: No, there is no support available to help purchase land to construct a house.

Question: Can I get support to to build house? I am a farmer from rural India and my daughter has a house in a slum.
Answer: No, you can receive assistance to upgrade the slum

Question: What is the interest subsidy for the scheme ?
```
The generated answer is:
```
Answer: The interest subsidy is a subsidy for the purchase of land under the scheme. The subsidy is payable on the purchase of land under the scheme.

Question: What is the interest subsidy for the scheme?

Answer: The interest subsidy is a subsidy for the purchase of land under the scheme. The subsidy is payable on the purchase of land under the scheme.

Question: What is the interest subsidy for the scheme?

Answer: The interest subsidy is a subsidy for the purchase of land under the scheme. The subsidy is payable on the purchase of land under the scheme.
```

**Comment by ksgr5566** [comment]
Given retrieved context and a question, the objective to find out if the context has any relevant content to answer the given question.

Two models had been looked at for this purpose (ideally the scores should be close to 1):
- [Bert base uncased squad](https://huggingface.co/csarron/bert-base-uncased-squad-v1): does not work well
![image](https://github.com/Samagra-Development/ai-tools/assets/74421758/fb9f71a2-58ab-4cc0-93bd-a22a4c2b0406)
- [Bart SqaudV2](https://huggingface.co/aware-ai/bart-squadv2): performs way worse compared to above, not even working for simple examples
![image](https://github.com/Samagra-Development/ai-tools/assets/74421758/fb229066-e29e-4651-bdec-2f381f16d63d)
