### ISSUE TITLE
Data creation for coreference resolution ( synthetically)

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#174]

**Comment by ksgr5566** [comment]
Having trouble generating data with GPT; it is unable to accurately generate examples having explicit coreferences in the final question of the input (Q, A, Q). It is also unable to properly identify and resolve coreferences (identifying entities belonging to the same cluster) for all cases.

Used GPT-3.5 api [here](https://colab.research.google.com/gist/ksgr5566/c90561ac9ce6ad76eb94410dc6323c3a/gpt4-api-access.ipynb).
Sample conversations with GPT-4: [PROMPTS.md](https://github.com/Samagra-Development/ai-tools/files/12016287/PROMPTS.md).

In short, GPT is having trouble properly identifying "clusters" and "cluster_strings" required for training fastcoref, or in general, clusters are needed by any coreference resolution model.

The current plan is to:
1. Use GPT to generate conversational data in the following format:
    - Input: Q, A, Q
    - Output: Q
    The output should be - final Q in the input but modified to include the contextual information.
2. Try to find a way to generate cluster information (cluster_strings along with their character numbers that is required for "clusters" section on fastcoref training format) by passing in the Input, Output generated in step 1. Logic here is, now that the task is divided into 2 parts, first generating conversations and next identifying clusters, GPT would better handle the task.

---

Update 1:
- Step 1 doesn't seem to work, refer to [PROMPTS.md](https://github.com/Samagra-Development/ai-tools/files/12016287/PROMPTS.md).
