### ISSUE TITLE
Training fcoref for our data

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#182]

**Comment by singhalkarun** [comment]
Closing this as implemented by @ksgr5566. @ksgr5566 can you please reference the PR here for future reference?

**Comment by ksgr5566** [comment]
There was a problem with generating data for training fcoref as mentioned [here](https://github.com/Samagra-Development/ai-tools/issues/174#issuecomment-1619736194). 

PR for integrating fcoref to AI-Tools: #206
