### ISSUE TITLE
Comparison of coref resolution models

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#183]

**Comment by Gautam-Rajeev** [comment]
@ksgr5566  Please update with results here so far

**Comment by ksgr5566** [comment]
Results on 60 [testcases](https://github.com/ksgr5566/coref/blob/main/tests/tests.json):
spacy model gives 27.12% acc while the fcoref model gives 33.89% with 0.9 as threshold on cosine similarity. 76.28% with bart-large model.

Breakdown:
Spacy : 30.7% acc. (explicit corefernce cases)
            26.08% acc. (remaining)
Fcoref : 61.53% acc. (explicit coreference cases)
             26.08% acc. (remaining)
Bart-lg : 69.2% acc. (explicit coreference cases)
              78.2% acc. (remaining)
              
Bart-lg performance is a bit better than reported: for some predictions it adds more information then required, while it is not wrong, compared to true output the cosine similarity drops. Look at it's predictions [here](https://github.com/ksgr5566/coref/blob/main/tests/hf_results.csv) for a better picture.

The reason for 26.08% acc. on other cases for fcoref and spacy is, other cases include tests where coreference is not required, it should not be considered as resolving that percentage of implicit coreferences as that is not possible by these models.

**Comment by Gautam-Rajeev** [comment]
closing this with the above as final results
