### ISSUE TITLE
Create simplistic UI to know progress on synthetic data modelling pipeline

### ISSUE THREAD

**Issue by GautamR-Samagra** [Samagra-Development/ai-tools#184]

**Comment by ksgr5566** [comment]
The backend API makes possible the following:
1. view data samples generated from gpt, specified by the prompt.
2. if the data generated is acceptable using the prompt generated, the same prompt can be used to generate data which can be stored as a hugging face dataset.
3. additional data can be generated and be added to the previously generated dataset.
4. the dataset can be used to finetune a specified model which will be stored as a hugging face model.
5. different version numbers of the model are provided associated with the update dates.

UI should focus on making this funcionality easily accessible. Every UI session should be initialized with two api keys (HF, OpenAI) which are required for interacting with the API.
