### ISSUE TITLE
Resolve implicit coreferences

### ISSUE THREAD

**Issue by ksgr5566** [Samagra-Development/ai-tools#188]
Main ticket - #42 

Consider the below input for coreference resolution:
```
Q: How do I protect my plants from frost?
A: To protect plants from frost, cover them with frost blankets or use methods like overhead sprinkling to create a protective ice layer.
Q: When should I remove the frost protection?
```

Ideal output having contextual information would be:
```
 Q: When should I remove the frost protection for my plants?
```

The issue is that there is no explicit referencing term such as "them" in the input. For example:
```
Q: When should I remove the frost protection for them?
```
A neural coreference resolution model can identify "them" here belongs to "my plants"/"plants" and resolves (replaces) the coreference giving us the required output.

### Tasks
- Given a sentence, identify whether it actually needs an explicit reference.
- In case it needs an explicit reference, identify what kind of reference it would require. For example, instead of "them" if you append "it" to the above input, the model may not coreference "it" to "plants" since "plants" is a plural term. 
- (Or) Identify any other approaches to solving this issue (using lightweight LMs) as I feel the preceding task is as complex as coreference resolution itself. It makes more sense to identify the term "plants" directly rather than "them".

<hr>

More examples:

#### Example 1:
```
Q: How to treat for blast pest?  
A: To treat for blast pest in rice, you can treat the seeds with Pseudomonas fluorescens 
Q: What about brinjal?
```
For our use case the model should modify the last question to 
```
Q: What about blast pest treatment for brinjal?
```
As there is no entity referencing the "blast pest treatment" explicitly, a coreference resolution model cannot resolve anything here but if the question is slightly modified to 
```
Q: What about it in brinjal?
```
the model can then resolve "it" with "blast pest" which matches with the required output.

#### Example 2:
```
Q: How often should I feed my cat?
A: Cats should generally be fed twice a day, but the specific feeding schedule may vary depending on factors such as age, health condition, and dietary requirements.
Q: What if my cat has diabetes and requires a specialized diet?
```
The above conversation is valid, it is implicit that the user wants to know "how to feed the cat when it requires a specialized diet". A simple coreference resolution model would not work as this is outside its use case.

**Comment by Gautam-Rajeev** [comment]
No resolution found. using fcoref itself.
