### ISSUE TITLE
Setup Fairseq on Azure VM

### ISSUE THREAD

**Issue by singhalkarun** [Samagra-Development/ai-tools#190]
Github Link:

https://github.com/facebookresearch/fairseq

Reference Collab:

https://colab.research.google.com/drive/1PLiiNnDDPZvRvtqwfYHxN8RfD5s0IXqH?usp=sharing

Steps to test:

curl -X POST -F "wav_file=@"wav_audio_anorexia prevention odia.wav"" http://localhost:5000/speech_to_text

**Comment by ArjunYaduvanshi02** [comment]
!!

**Comment by ArjunYaduvanshi02** [comment]
for the public key:



ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9amefyKqqthofyLkmUKYRH3v2IfQRcjam1Hn6X3zHU0LZvdEqtppS7OY6cFlvQdBF7hH/g8Z5ugmCGpjchrmzTtizHrk//ql2exRKlU7Eu94LuhJ6xRapXxMrroDEzA+d4FQu9Qynb420VCsT7CzaJ5G2qGb+mezVcVjhjnTxDnuZkrt5ITAzeEUPS9XV1Y6nTDzk8efNKvpnXa97nKiZBsajPb1WaXOByK4bdrMoC4PbOGmx7eOdhdvwaQmfMX636Sy9qNgQgSfPf/IuihwElRtHGnpd0hk6ID49weprZKJQ4Yp15X6Txy9KFLO0+0o2gCkt3EZkOLPJs8JKX18GpME2vEGWPbpk0TcFxS0j07DC/Mt1TNcs9VsWmG/RfrpDnXXPoP6F1ROTQov0z5bzNnMsYvDTjzM3gFRZdrYT2qHa88IXk7NeO/WAaQ/arGBddkifi3BFEAvgzHz9hXqSJCroewswIZMzqHDXET+1kbeO3DjfEdjk2ez56nlpTNM= sasuke@DESKTOP-7LFPQ6K

**Comment by singhalkarun** [comment]
<img width="1391" alt="CollabDetails" src="https://github.com/Samagra-Development/ai-tools/assets/113603846/26506ddc-1944-4610-a14b-e56ebcd3f5ba">

**Comment by ArjunYaduvanshi02** [comment]
[Untitled document.pdf](https://github.com/Samagra-Development/ai-tools/files/11998196/Untitled.document.pdf)

reference material and links

**Comment by singhalkarun** [comment]
Closing this as implemented an internal team.
