### ISSUE TITLE
Accessing Vault from Ansible

### ISSUE THREAD

**Issue by Manas23601** [Samagra-Development/ai-tools#192]
I have a created a Hashicorp Vault in an EC2 machine by using a docker image.
I'm able to access the vault outside EC2 and in my terminal by executing `vault login <token>` command.
I have created two keys in the following path `secret/github`. 

I am able to access these secrets by `vault kv list secret=secret/github` and  `vault kv get secret/github/username`  both in my terminal and ansible script.

When I try to do the same with a `lookup` command in my ansible script, it is failing.  I get an error message stating secret path does not exist.

![image](https://github.com/Samagra-Development/ai-tools/assets/68193537/355875d1-4d13-4561-9da1-675a817be3fd)

P.S:

Root Cause Analysis:

The issue was occurring due to an incorrect version number of the vault. Required version is number `2.0` but  `1.0` was used. 
Update it as follows: `vault secrets enable -version=2 -path=secret kv`

**Comment by singhalkarun** [comment]
@Manas23601 

```I'm able to access the vault outside EC2 and in my terminal by executing vault login <token> command.```

Are you able to run vault login successfully from the machine inside? Can you share response screenshot both for from inside machine and outside machine?

**Comment by Manas23601** [comment]
Yes, I'm also able to do that.

**Comment by singhalkarun** [comment]
> Can you share response screenshot both for from inside machine and outside machine?

Can you detail out all steps? Like command you used to start vault? then command you used to login? Avoid sharing any secrets/token here though. Have you opened access to port on machine on which vault is listening to?

**Comment by singhalkarun** [comment]
> I have a created a Hashicorp Vault in an EC2 machine by using a docker image. I'm able to access the vault outside EC2 and in my terminal by executing `vault login <token>` command. I have created two keys in the following path `secret/github`.
> 
> I am able to access these secrets by `vault kv list secret=secret/github` and `vault kv get secret/github/username` both in my terminal and ansible script.
> 
> When I try to do the same with a `lookup` command in my ansible script, it is failing. I get an error message stating secret path does not exist.
> 
> ![image](https://user-images.githubusercontent.com/68193537/252232947-355875d1-4d13-4561-9da1-675a817be3fd.png)

In lookup plugin, can you please try using path, secret/data/github?

**Comment by Manas23601** [comment]
I'm still getting the same issue:  

`fatal: [fd01:db8:1111::3]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: The secret 'secret/data/github' doesn't seem to exist.. The secret 'secret/data/github' doesn't seem to exist.")`

**Comment by singhalkarun** [comment]
RCA: https://github.com/Samagra-Development/ai-tools/issues/192#issue-1795973469
