### ISSUE TITLE
Create public playground for ai-tools

### ISSUE THREAD

**Issue by Gautam-Rajeev** [Samagra-Development/ai-tools#193]
## Create UI for user to input PDFs and answer questions based on the PDF :

UI should be similar to https://www.chatpdf.com/, right side should be the conversational flow (Agri mitra ) , left should allow certain options for the user to choose.  

It has a bunch of API's  :  
-  Language detection (Use Bhashini APi's) 
- Language translation (Use Bhashini API's ) https://github.com/Samagra-Development/ai-tools/tree/restructure/src/text_translation/ai4bharat/batch
- Document upload and chunking of document (needs to be created ) - multiple options win be enabled in future- now (similarity trough splitting)  v1 of API to be created here :  https://github.com/Samagra-Development/ai-tools/issues/200 ETA : 21/07/2023
- Create embedding for document - multiple options for embedding to be deployed - now : 
    - openai embedding 
    -  instructor model 
    - COLBERT 
  v1 of API to be created here (not ColBERT)-  https://github.com/Samagra-Development/ai-tools/issues/199  ETA : 19/07/2023
- Neural coreference (using spacy model for now, BART to be enabled for later ) 
  https://github.com/Samagra-Development/ai-tools/issues/203 ETA 19/07/2023
   https://github.com/Samagra-Development/ai-tools/issues/202 ETA 21/07/2023
   https://github.com/Samagra-Development/ai-tools/issues/201 ETA 23/07/2023

- Question answering : 
     - DSP 
     - Simple context  prompt  {BFF} 

## Chat with schemes :  
UI to take as input as 'user prompt' and 'json file' and maps the 'json keys' to entities from user prompt.  

## Allowing the deployment of the entire setup as docker file : 
https://drive.google.com/file/d/1TW2yqyCrJcL3sEkuWfy3sQC8IpEvCfR-/view?usp=sharing 

@karun to add details for this. This allows a user to get a local deployment via a docker file once they have selected all the options in each block

**Comment by Amruth-Vamshi** [comment]
.
