### ISSUE TITLE
Api for embedding content and prompt

### ISSUE THREAD

**Issue by Gautam-Rajeev** [Samagra-Development/ai-tools#199]

**Comment by singhalkarun** [comment]
Closing as implemented by @H4R5H1T-007. @H4R5H1T-007 Please link the PR for future reference.

**Comment by singhalkarun** [comment]
Closing as implemented by @H4R5H1T-007. @H4R5H1T-007 Please link the PR for future reference.

**Comment by H4R5H1T-007** [comment]
Here's Link to RP for future Reference.
https://github.com/Samagra-Development/ai-tools/pull/205
