### ISSUE TITLE
Make models in startup and use GPU when available for all models

### ISSUE THREAD

**Issue by tushar5526** [Samagra-Development/ai-tools#219]
Reference -  https://github.com/Samagra-Development/ai-tools/pull/218

**Comment by Manas23601** [comment]
@singhalkarun are we going to do this in docker compose itself? What about Kubernetes YAML files?

**Comment by singhalkarun** [comment]
Closing as another similar issue exists #220

**Comment by singhalkarun** [comment]
Closing as another similar issue exists #220
