### ISSUE TITLE
Convert National Education Policy document to a structured json file with required headings

### ISSUE THREAD

**Issue by Manas23601** [Samagra-Development/ai-tools#235]
# Objective
Improve the Chunking algorithm to collect additional information about the Text Chunks

## What we have now
- Start page and End page for each Chunk

## What we need
- Chunk ID an Image belongs to
- More information about each Chunk i.e (Grouped under which heading)

# Proposed Solutions

## Observations
- Fonts and Text Formatting is lost when extracting text from the PDF
- Images are not extracted from the PDF
- Extracted Text is not in chronological order.

### Using Regular Expression 
Search for headings (ex 1.4.1 or 1.6.31) in each chunk. Based on the number, we can group chunks under a heading.

#### Flow:
- An Iterative approach.
- Loop through each small chunk.
- Check if a heading exists ( if it does, update heading counter)
- Go to the next chunk.

Group the chunks later based on the Headings. 

### Commercial Software
- Use Adobe to convert PDF to XML.
- Online Tools to convert PDF to HTML

### PDF to XML

1. PDFQuery can convert any PDF Document to XML. 
2. Use an XML parser to identify common fields that corresponds to headers in each XML tag

### PDF To HTML
- PDFPlumber (Identifies font?)
- PdMuPDF (For Images)

### OCR on PDF

1. Use an OCR Algorithm to identify text paragraphs in the document
2. Process it later to identify headers and text paragraphs.

### PDF to XML
- Used PDFQuery to convert PDF to XML.
- Index attribute in XML tags seemed to be in chronological order in the pDF but, it wasn't consistent.

### PyMuDF
- Extracts Text similar to PDFquery. Doesn't highlight font differences.

### pdfplumber
- Is able to identify font but it is for individual characters. 

[Code Examples](https://github.com/Manas23601/ai-tools/tree/PDFChunking/ChunkingExamples)

### Use Clip framework to map Images with text
[Google Colab](https://colab.research.google.com/drive/1dtIgnFdyLK-dZjBNdbp1_C7L-QiE6wLN?usp=sharing)

**Comment by Gautam-Rajeev** [comment]
Final table should look like this -  https://docs.google.com/spreadsheets/d/1q-aWJFUAlFHr_yNOwv5XNPgbg-Ghk7DuBiKdYm05MV4/edit#gid=1851889542

**Comment by Gautam-Rajeev** [comment]
Data folder with  the images of the chapters - [Link](https://drive.google.com/drive/folders/1LftFGwQDWxHyTE5B0rJzSQumQ885U66o)

Using clip to associate images to the text chunks - [Link](https://www.google.com/url?q=https://colab.research.google.com/drive/1dtIgnFdyLK-dZjBNdbp1_C7L-QiE6wLN?usp%3Dsharing&source=gmail&ust=1693894210373000&usg=AOvVaw0_KCQrQugpD8aRCEXsV5T7)

Layout parsing code (to get json from the pdf pictures) - [link](https://colab.research.google.com/drive/1Ki7GgF5tvGR9RQW28ajk5ncx3CAHFfYY?usp=sharing) we need to use data folder with the images here to extract structure from each image

Chapter 1 output so far -
- json flattened - [Link](https://drive.google.com/file/d/16zxq7hMw_jSdpj0fjjvB_Wg-Rt02zK40/view?usp=drive_link)
- json - [Link](https://drive.google.com/file/d/1NZZH3ngWOgrzYE2KNLbn-dWqe0uzI0ca/view?usp=drive_link)

**Comment by TakshPanchal** [comment]
.

**Comment by Gautam-Rajeev** [comment]
@TakshPanchal you can take up creating the json for the entire book and share with Sai 
@ksgr5566 can you take up matching the images for each page with the json structure being created above. 
@ksgr5566 stitch all of the code together - to create the table in the final structure shown above. 
@ksgr5566 we need to similarly identify tables after this (like images)

**Comment by Gautam-Rajeev** [comment]
The first chapter parsed above is [here](https://drive.google.com/file/d/1vRrdplWADLhjd9BI-WW3lnm_B5ZdXtGH/view?usp=drive_link)

Wanted to explore how do we extract information out from then image on page 31 so as to answer questions like : 
1. Which are the curricular areas and how are they related to the vision of society ? 
2. How does school culture fit in within NEP ?

**Comment by ksgr5566** [comment]
> @TakshPanchal you can take up creating the json for the entire book and share with Sai @ksgr5566 can you take up matching the images for each page with the json structure being created above. @ksgr5566 stitch all of the code together - to create the table in the final structure shown above. @ksgr5566 we need to similarly identify tables after this (like images)

Regarding images: PDF reader (`fitz` library) retrieved 1261 total images. I removed images that were repetitive, since if an image repeats it would be a decorative image. Doing that, reduced the total number of images to 47. Now these images are matched with text chunks using CLIP.

PFA for different parts of the pdf:
[a.csv](https://github.com/Samagra-Development/ai-tools/files/12671826/a.csv)
[b.csv](https://github.com/Samagra-Development/ai-tools/files/12671827/b.csv)
[c.csv](https://github.com/Samagra-Development/ai-tools/files/12671828/c.csv)
[d.csv](https://github.com/Samagra-Development/ai-tools/files/12671832/d.csv)
[e.csv](https://github.com/Samagra-Development/ai-tools/files/12671834/e.csv)

[extracted_images.zip](https://github.com/Samagra-Development/ai-tools/files/12671868/extracted_images.zip)

**Comment by Manas23601** [comment]
@GautamR-Samagra, how much better would knowledge graphs embeddings be than sequential text extractions for reasoning based queries?
