### ISSUE TITLE
Not responding to questions (Bugs/Latency Issues)

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#278]
- [ ] Quality of answers is fine. Do a series of tests with @Amruth-Vamshi to see the logs.
     - [x] First shot works fine
     - [ ] Follow up questions
- [ ] Latency High => T2S on the frontend (Prateek), Translation - switch to Azure.
     - [x] S2T - Bhashini
     - [x] T2S - Bhashini - latency OK
     - [x] Translation hi to en - Azure
     - [x] Translation en to hi - Azure
     - [ ] Summarization/Reasoning - GPT 3.5 - Slow (24s)
- [x] @ChakshuGautam Web Whisper (T2S, S2T) as backup (not needed)

**Comment by aashutosh-samagra** [comment]
.

**Comment by ChakshuGautam** [comment]
POCs for Streaming responses

- [x] Stream text from GPT to client through WebSocket
- [x] Stream audio to the client through WebSocket

Bugs
- [ ] Update ChatHistory by calling an API
- [ ] Parsing issues - Sentence function update - every punctuation mark;
    - [ ] `1.` is not handled
    - [ ] `...` not handled
    - [ ] Pause not getting handled?

**Comment by ChakshuGautam** [comment]
- [ ] Details on time taken

**Comment by aashutosh-samagra** [comment]
- [ ] Search for docs latency is slow - @ChakshuGautam

**Comment by ChakshuGautam** [comment]
@aashutosh-samagra to add examples.
