### ISSUE TITLE
Add Ragatouille Retriever API

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#288]
## Description
Need to be able to deploy Colbert on a server such that one can update index in it using an API call. 

## Current State 
We are able to deploy ColBERT locally using [RAGAtoullie ](https://llamahub.ai/l/llama_packs-ragatouille_retriever?from=llama_packs) in our local systems. 
Our current vector DB setup is PGvector. 

## Implementation Details 
We want to be able to setup RAGAtoullie/COLBERT on a server such that content can be retrieved quickly.  
It should be able to do the following : 
- Be able to contain multiple indexes (I want to index the headings separately and content separately etc)
- Be able to update any index through an API 
- Be able to run search on any of the index and get retrieved doc, index and , index-number through an API
- Contributors can raise PRs such that it works as an API service, can add as a separate folder COLBERT to ai-tools/src/search/...

## Product Name
AI Tools

## Organization Name
SamagraX

## Domain
NA

## Tech Skills Needed
Pytorch/ Python, ML

## Category
Feature

## Mentor(s)
@ChakshuGautam 

## Complexity
Low

**Comment by J0SAL** [comment]
I would like to work on this issue  @ChakshuGautam

**Comment by Shruti3004** [comment]
Hey @J0SAL, yes sure. Assigning the ticket to you.

**Comment by Ayushmaan06** [comment]
I would love to work on the issue.

**Comment by kartikf4** [comment]
by server you meant cloud server right?

**Comment by ChakshuGautam** [comment]
@kartikf4 see the other modules in ai-tools. Example - https://github.com/Samagra-Development/ai-tools/tree/restructure/src/llm/openai/chatgpt3. It's an independent module that we add.

**Comment by J0SAL** [comment]
Hi @Shruti3004, can you assign it to someone else, as i won't be able to make it

**Comment by masterismail** [comment]
hey ! the link mentioned (https://llamahub.ai/l/llama_packs-ragatouille_retriever?from=llama_packs) gives a 404.

**Comment by Gautam-Rajeev** [comment]
> hey ! the link mentioned (https://llamahub.ai/l/llama_packs-ragatouille_retriever?from=llama_packs) gives a 404.

You can use any implementation of [RAGAToullie](https://github.com/bclavie/RAGatouille) or [ColBERT ](https://github.com/stanford-futuredata/ColBERT) directly

**Comment by vandit98** [comment]
hi @Shruti3004 @ChakshuGautam @GautamR-Samagra 
I am interested in this project. I have experience in building API endpoints via Fastapi , RAG pipelines, and vector databases.
Can you assign this ticket to me. Also, details on the current state of the project will be appreciated. I have also gone through the RAGatouille, i will soon share the project implementation plan.
Thank you.

**Comment by Sanika-k-1317** [comment]
Hello @ChakshuGautam @Shruti3004 @GautamR-Samagra 
I am interested to contribute in this project. I have experience working with Pytorch. Please let me know how to connect with you for further discussion. Also could you please assign the ticket to me?

**Comment by Gautam-Rajeev** [comment]
Have also added COlbert to ai-tools myself [here](https://github.com/Samagra-Development/ai-tools/tree/restructure/src/embeddings/colbert/local) to allow to run on a [collab ](https://colab.research.google.com/drive/1CGzS7R7Vb6wZnfy-pLTDcrWxODJa1wLl?usp=sharing) through that. 

Has a few issues : 
- unable to setup on Azure yet because of cuda issues. If it can be setup within Docker by someone, that would be immensely useful. 
- updating the  created index with new sentence
- set up fine-tuning the model based on new question-answer pairs

**Comment by Sohajawdekar** [comment]
Hey @ChakshuGautam @Shruti3004 @GautamR-Samagra !
I am interested in contributing to this project, and working on the prerequisites. Could you please assign this issue to me ?

**Comment by Gautam-Rajeev** [comment]
Hi @Sohajawdekar , this has been picked up and completed  by @takshpanchal

**Comment by Gautam-Rajeev** [comment]
@takshpanchal do tag the pr raised finally here
