### ISSUE TITLE
RAPTOR Implementation

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#293]
### Tasklist
Implement the paper.

### References
- [Paper](https://arxiv.org/pdf/2401.18059.pdf)

**Comment by Gautam-Rajeev** [comment]
@xorsuyash assigning this to you 
Can use this for [summary](https://github.com/Muhtasham/summarization-eval)

**Comment by xorsuyash** [comment]
@ChakshuGautam @GautamR-Samagra 

- recursive clustering implementation 
- summarization implementation 
- traversal implementation ( tree traversal + collapsed tree)
- comparing results with other retriervers like colbert...etc

**Comment by xorsuyash** [comment]
@ChakshuGautam ,@GautamR-Samagra I have initiated the implementation of RAPTOR https://github.com/xorsuyash/pyraptor , 
I have also reached out Aditi tuli one of the author of research paper they will make the code public soon , should i ask them to collaborate with us in implementing it as a python library ?

**Comment by Gautam-Rajeev** [comment]
https://github.com/run-llama/llama_index/blob/main/llama-index-packs%2Fllama-index-packs-raptor%2Fexamples%2Fraptor.ipynb

**Comment by ChakshuGautam** [comment]
Can we change this ticket to summarizing using RAPTOP given the implementation is already closed?
