### ISSUE TITLE
compare and reimplement Agri classification models

### ISSUE THREAD

**Issue by Gautam-Rajeev** [Samagra-Development/ai-tools#300]
- use the dataset provided [here](https://huggingface.co/datasets/GautamR/akai_flow_classifier_seed_pest_scheme) 
- use code reference [here](https://colab.research.google.com/drive/11Uh-S-mATsg5KRzUSxx_1NeUQ7ROxNbC?usp=sharing)
-  compare between [BERT](https://huggingface.co/docs/transformers/en/model_doc/bert), [DeBERTAv2](https://huggingface.co/docs/transformers/en/model_doc/deberta-v2), [DistilBERT ](https://huggingface.co/docs/transformers/en/model_doc/distilbert),  [MobileBERT](https://huggingface.co/docs/transformers/v4.39.0/en/model_doc/mobilebert) and provide comparision on speed vs accuracy on nvidia t4gpu and cpu. use provided accuracy and f1 score as metrics.

**Comment by smokeyScraper** [comment]
can you assign this to me? I can work on this

**Comment by Gautam-Rajeev** [comment]
closed by @jiya126 [here](https://github.com/BharatSahAIyak/ai-tools/pull/69)
