### ISSUE TITLE
Fine tune on hindi dataset and convert it to TFLite

### ISSUE THREAD

**Issue by Gautam-Rajeev** [Samagra-Development/ai-tools#318]
## Whisper has some small issue now with translating last to input language : 

https://huggingface.co/openai/whisper-large-v3/discussions/71
https://github.com/huggingface/transformers/pull/28687

** this is just a bug we might face later on and just calling  it out now .  

## We can fine tune whisper :  
https://huggingface.co/blog/fine-tune-whisper

[Medium](https://medium.com/@shridharpawar77/a-comprehensive-guide-for-custom-data-fine-tuning-with-the-whisper-model-60e4cbce736d)

### Dataset: 

https://ai4bharat.iitm.ac.in/shrutilipi/

https://ai4bharat.iitm.ac.in/indicsuperb/

https://ai4bharat.iitm.ac.in/indicvoices/#:~:text=INDICVOICES%20is%20a%20dataset%20of,Indian%20districts%20and%2022%20languages 

Collating indic voices :  https://colab.research.google.com/drive/1HeRjs7MxQngZRybnxldm1Yq5lqR6Qqvr#scrollTo=q82yn54YCD_e

## We can convert to TFlite model : 
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/notebooks/generate_tflite_from_whisper.ipynb

Its just a 40 MB quantized model -  https://github.com/openai/whisper/discussions/506

**Comment by Gautam-Rajeev** [comment]
@Jiya126

**Comment by Jiya126** [comment]
Hey, working on this issue

**Comment by Gautam-Rajeev** [comment]
tuning is done , converting to tflite remaining, raising it as a separate ticket
