### ISSUE TITLE
Create a fine grained access token for pushing docker images to github packages

### ISSUE THREAD

**Issue by singhalkarun** [Samagra-Development/ai-tools#40]
## Description
Create a fine-grained access token that allows pushing Docker images to GitHub Packages.

## Goals
- [ ] Generate a new access token with the necessary permissions for pushing Docker images to GitHub Packages
- [ ] Configure the access token to have fine-grained permissions limited to the required repositories and packages
- [ ] Document the access token and its usage for future reference

## Expected Outcome
The access token will provide the necessary credentials to push Docker images to GitHub Packages. By creating a fine-grained access token, you can ensure that it only has the required permissions and restrict access to specific repositories and packages, enhancing security and access control.

## Acceptance Criteria
- [ ] A new access token is generated specifically for pushing Docker images to GitHub Packages
- [ ] The access token is configured with fine-grained permissions limited to the necessary repositories and packages
- [ ] The access token is documented, including its usage and any expiration or renewal instructions

## Implementation Details
[List any technical details about the proposed implementation, including any specific technologies that will be used.]

## Mockups / Wireframes
[N/A]

---

## Project
AI-tools

## Organization Name:
Samagra

## Domain
Social Welfare

## Tech Skills Needed:
GitHub, Docker

## Mentor(s)
@ChakshuGautam

## Complexity
Medium

## Category
DevOps

## Sub Category
Credentials Management

**Comment by yashika9536** [comment]
I am interested in this project and want to contribute.

**Comment by shubhigupta991** [comment]
I want to contribute to this project

**Comment by mecskyverse** [comment]
Hey, @singhalkarun just wanted to clarify is this issue for everyone like anybody can generate this token or do people with ai-tools package access or ownership need to make this token?

**Comment by singhalkarun** [comment]
Closing this as irrelevant. This was only meant for internal uasge.
