### ISSUE TITLE
Update workflow to make package public while pushing to github package and also automatically connect it to repository

### ISSUE THREAD

**Issue by singhalkarun** [Samagra-Development/ai-tools#41]
## Description
Update the workflow to make a package public and automatically connect it to the repository in GitHub Packages.

## Goals
- [ ] Modify the workflow to configure the package to be public upon pushing it to GitHub Packages
- [ ] Automate the connection of the package to the repository
- [ ] Ensure the workflow runs smoothly and the package is accessible to users

## Expected Outcome
The updated workflow will automatically make the package public and establish a connection to the repository in GitHub Packages. This ensures that the package is easily accessible and discoverable by users who can benefit from its functionalities.

## Acceptance Criteria
- [ ] The workflow is updated to include the necessary configuration for making the package public
- [ ] The workflow automatically establishes a connection between the package and the repository in GitHub Packages
- [ ] The package is accessible and visible to users in GitHub Packages

---

## Project
AI-tools

## Organization Name:
Samagra

## Domain
Social Welfare

## Tech Skills Needed:
GitHub Actions

## Mentor(s)
@ChakshuGautam

## Complexity
Medium

## Category
DevOps

## Sub Category
Maintenance

**Comment by mecskyverse** [comment]
Hey @singhalkarun @GautamR-Samagra can you assign me this issue.

**Comment by SoumyadipYT-OSS** [comment]
I am interested in working on the project of updating the workflow to make the package public while pushing to GitHub package and also automatically connect it to the repository. I have experience in using GitHub actions, which is a skill set needed for this project. I am confident that I can contribute to this project and learn from it.

**Comment by Shurtu-gal** [comment]
@singhalkarun Can I work on this issue?
I have prior experience in building actions as well as writing workflows.
https://github.com/asyncapi/.github/pull/262
https://github.com/Shurtu-gal/autoupdate-fork-action
