### ISSUE TITLE
Debug Server doesn't track src folder

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#45]
The server doesn't restart when changes to src folder happens.

**Comment by Nazi-pikachu** [comment]
Hi @ChakshuGautam I would like to work upon this issue.
Can you please assign this to me.

**Comment by Nazi-pikachu** [comment]
@ChakshuGautam 
Can you provide more context regarding what is expected to happen when changes to src folder is being done.
Right now when changes are made to src folder , its getting reflected in the new api call

**Comment by ChakshuGautam** [comment]
Hey when I make changes to the src folder on a debug server for quart, it doesn't reload the dev server. It reloads when you make changes to the server file. Need to ensure that happens for all server. 

Currently, it doesn't happen because of dynamic imports. Need to figure out how to keep dynamic imports and ensure src is not removed because of tree shaking.

**Comment by Nazi-pikachu** [comment]
@ChakshuGautam 
I am thinking of using [WatchDog](https://python-watchdog.readthedocs.io/en/stable/quickstart.html#a-simple-example) to setup an observer and event handler on src. 
Do you think this will work or have any other suggestion for me regarding this issue.

**Comment by Nazi-pikachu** [comment]
@ChakshuGautam 
Can you please share your opinions on this approach
