### ISSUE TITLE
Add a header to the response when it comes from a cached function

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#46]
## Description
Add a header to the response when it comes from a cached function to indicate its origin.

## Goals
- [ ] Modify the function logic to include a header in the response when it is served from a cached function
- [ ] Define a custom header, such as `ai-tools-cached`, to indicate that the response is from a cached function
- [ ] Ensure the header is included in the response for appropriate requests

## Expected Outcome
By adding a header to the response from a cached function, it becomes possible to differentiate between responses served from cache and those generated in real-time. This information can be useful for debugging and monitoring purposes, allowing developers to understand the performance and behavior of the cached functions.

## Acceptance Criteria
- [ ] The function logic is updated to include a custom header, such as `ai-tools-cached`, in the response when it comes from a cached function
- [ ] The header is included in the response for appropriate requests
- [ ] The presence of the header accurately indicates whether the response is from a cached function or not

## Project
AI-tools

## Organization Name:
Samagra

## Domain
Social Welfare

## Tech Skills Needed:
Backend Development

## Mentor(s)
@ChakshuGautam

## Complexity
Medium

## Category
Backend

## Sub Category
API Development

**Comment by Poonam1607** [comment]
@ChakshuGautam Can I work on this issue?

**Comment by Soumya1007** [comment]
I would like to work on this

**Comment by Poonam1607** [comment]
Hey @ChakshuGautam! Can you please review my PR?

**Comment by ChakshuGautam** [comment]
Hey @Poonam1607 commented on the PR.

**Comment by Pyasma** [comment]
Hey @ChakshuGautam,

Can I work on this issue? I'm available and interested in rewriting the api.py files for each model.

Please let me know if I can proceed with this. Thank you!

**Comment by Pyasma** [comment]
Hey @ChakshuGautam,

Can I work on this issue? I'm available and interested in working on this issue

Please let me know if I can proceed with this. Thank you!

**Comment by ChakshuGautam** [comment]
Please create a checklist for models, raise a draft PR, and add commits per model so that others can contribute and see your code for the PR as well.

**Comment by Pyasma** [comment]
Sure, I will start working on it.

**Comment by ShubhamBhut** [comment]
Hey @ChakshuGautam , I think the used async-cache module currently don't have any support to check if the cache was used in response or not. I think I would have to first implement it there and then I can start working on this issue.
Can you pls tell me if there is any other way to solve this issue ?
Also I have a query that why we need a header for this, can't we just return 200 (from cache) or 304 ?

**Comment by vishvjeet-thakur** [comment]
Can I try this issue?

**Comment by vishvjeet-thakur** [comment]
I think one of the approach to this issue could be modifying call method  of  Async TTL decorator.

**Comment by rushi-02** [comment]
can i work on this issue?

**Comment by vishvjeet-thakur** [comment]
@ChakshuGautam  sir please review my PR #189  for this issue
