### ISSUE TITLE
Verify Response Format

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#53]
- [ ] Add response format to [repository](https://github.com/Samagra-Development/ai-tools/blob/main/repository_data.json)
- [ ] Verify response format before sending it back [here](https://github.com/Samagra-Development/ai-tools/blob/02e35480354c960e2d4166bd0eface5a32c829bd/api.py#L103)

**Comment by ArjunYaduvanshi02** [comment]
can i work on this issue @ChakshuGautam Sir?

**Comment by ChakshuGautam** [comment]
Hey can you share your approach before you raise a PR?

**Comment by ChakshuGautam** [comment]
Hey can you share your approach b fore you raise a PR?

**Comment by ArjunYaduvanshi02** [comment]
@ChakshuGautam Sir, after hours of research I finally prepared a response format that includes several fields, such as success to indicate whether the request was successful, as well as error to provide information on any errors that occurred, and the data feild that contain a name and a set of models that can be used for that use case.Lets take a usecase("text translation") as an example it include models from ai4bharat and bhashini, while the embeddings use case only includes models from openai.

**Comment by ArjunYaduvanshi02** [comment]
i also have validated the response format

**Comment by ChakshuGautam** [comment]
Is there a draft PR that I can see?

**Comment by ArjunYaduvanshi02** [comment]
yes sir i have created a draft PR. do check it and let me know

**Comment by ArjunYaduvanshi02** [comment]
@ChakshuGautam is it fine sir?

**Comment by ChakshuGautam** [comment]
I saw the PR but only found one file committed. Is that correct? Can you share the changes that you made and why in the PR itself?

**Comment by ArjunYaduvanshi02** [comment]
@ChakshuGautam Sir, the response format code written was also correct json response format but it was missing the success and error criteria. I hve modified the code for giving a success and error response if error occoured. otherwise the code is balanced and shows the use case under diffrent models for Natural Language Processing.
Let me know if you want to add any factor. I have verified the response format and it looks fine .

**Comment by ChakshuGautam** [comment]
Hey still couldn't see it in the PR. Can you actually share the code in this ticket and explain your process.

**Comment by ArjunYaduvanshi02** [comment]
[json.response.format.updated.pdf](https://github.com/Samagra-Development/ai-tools/files/11449276/json.response.format.updated.pdf)

**Comment by ArjunYaduvanshi02** [comment]
@ChakshuGautam Sir i have prepared a detailed report about my commit do check it and let me know

**Comment by ChakshuGautam** [comment]
Hey let's connect on discord and do this over a call. You can find me using the username "Chakshu (M)"

**Comment by ArjunYaduvanshi02** [comment]
Sure Sir!!
