### ISSUE TITLE
Refactor Remote Services

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#54]
Remote service onboarding should not include code changes. They should be onboarded directly through `repository.private.json` which overrides the `repository.json`

**Comment by fykaa** [comment]
Hey @ChakshuGautam  
I think I can work on this one real quick😀
Would want to get this assigned!

**Comment by ChakshuGautam** [comment]
Go for it

**Comment by singhalkarun** [comment]
Closing this as following a different format for model onboarding in case of multi image deployment.
