### ISSUE TITLE
Admin for AI Tools

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#55]
Setup [react admin](https://marmelab.com/react-admin/) for AI Tools. It should monitor
- [ ] Repository

(Undercooked issues)

**Comment by amankumar003** [comment]
hello @ChakshuGautam I'm Aman kumar , software developer and ML engineer, gone through the code base and wnat to ask you about " Write tests for your changes."

**Comment by singhalkarun** [comment]
@tushar5526 can we see if portrainer would be a good solution for this for monitoring?
