### ISSUE TITLE
Export Prometheus Metrics

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#56]
Something like [this](https://github.com/korfuri/django-prometheus) but for quart.

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by infinite8loop** [comment]
Hello,
I have prepared the docker-compose.yml for prometheus-cadvisor-grafana stack which exports the metrics from containers to Prometheus and can be monitored on grafana dashboard. Please let me know which branch do I consider as updated to create a PR. Thanks in advance.
@ChakshuGautam
This is the output for a demo container "redis", please let me know the updated branch for docker-compose to create a pr.

![image](https://github.com/Samagra-Development/ai-tools/assets/103845823/2b9697ed-85ea-4c08-9b22-311507f0a58b)

**Comment by singhalkarun** [comment]
Hey @tushar5526 can we see and try to implement similar solution as we did in agrimitra?
