### ISSUE TITLE
Add prometheus server

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#57]
## Description
Add Prometheus server to the project and update the Docker Compose file to include the necessary configurations.

## Goals
- [ ] Install and configure Prometheus server for monitoring the project
- [ ] Update the Docker Compose file to include the Prometheus service
- [ ] Define appropriate configurations and targets for Prometheus scraping

## Expected Outcome
By adding Prometheus server and updating the Docker Compose file, the project will have monitoring capabilities. Prometheus will be able to scrape metrics from the services defined in the Docker Compose file, providing valuable insights into the performance and health of the system.

## Acceptance Criteria
- [ ] Prometheus server is successfully installed and configured
- [ ] Docker Compose file is updated to include the Prometheus service
- [ ] Configurations and targets for Prometheus scraping are defined and working correctly

---

## Project
AI-tools

## Organization Name:
Samagra

## Domain
Social Welfare

## Tech Skills Needed:
Docker, Prometheus

## Mentor(s)
@ChakshuGautam

## Complexity
Medium

## Category
DevOps

## Sub Category
Monitoring

**Comment by wasup-yash** [comment]
Hey I would like to work on it can you provide relevant sources and info regarding that apart from the docker file which is needed.

**Comment by Poonam1607** [comment]
I would like to work on this issue.

**Comment by harshinirhsv** [comment]
I would like to work on this issue.

**Comment by VaibhaveS** [comment]
@ChakshuGautam can you review https://github.com/Samagra-Development/ai-tools/pull/94

**Comment by Neilblaze** [comment]
@ChakshuGautam I'm interested in this. Though I'm new to Prometheus, I'm able to delve deep without any hassle for now. Can I get some input on where to start?

**Comment by infinite8loop** [comment]
Hello,
I have prepared the docker-compose.yml for prometheus-cadvisor-grafana to monitor all the containers defined in the docker-compose file but I noticed there is already Prometheus defined in docker-compose (in main branch) but with no agent for prometheus to properly fetch metric. Please let me know which branch do I consider as updated to create a PR.
@ChakshuGautam

**Comment by infinite8loop** [comment]
This is the output for a demo container "redis", please let me know the updated branch for docker-compose to create a pr.
![image](https://github.com/Samagra-Development/ai-tools/assets/103845823/3b5fea22-dc40-4484-bcd0-9caa70395647)
