### ISSUE TITLE
Add a health check API

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#58]
Use [this](https://yaus.xyz/health) for any external dependent services.

- [ ] A global /health endpoint that allows to check health of each model.
- [ ] Update generate.sh to make health checks the part of generated docker-compose and nginx configuration file

**Comment by eternal-f1ame** [comment]
Can you assign this issue to me?

**Comment by ArjunYaduvanshi02** [comment]
can i also work on this issue?

**Comment by ArjunYaduvanshi02** [comment]
@ChakshuGautam Can you tell me where to add this health check api?

**Comment by singhalkarun** [comment]
> If we need to not only check if the model is up but also if the inferences are correct, don't we need to have unit tests for each model as well? @singhalkarun

There can be single /health endpoint inside each model's api.py file which allows us to know whether model is healthy or not. We can keep iterating over to improve over that /health endpoint.

**Comment by ayush0x00** [comment]
Please assign it to me

**Comment by singhalkarun** [comment]
Closing this as similar issue exists #155
