### ISSUE TITLE
Add Gitpod

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#59]
Gitpod setup for faster hacking and contributions.

**Comment by wasup-yash** [comment]
Hey, I would like to work on this issue.

**Comment by wasup-yash** [comment]
can u please explain the workflow for this particular issue?

**Comment by Poonam1607** [comment]
Hey @ChakshuGautam! Can you assign this to me?

**Comment by AdityyaX** [comment]
Hey , @ChakshuGautam 
I would like to work on this issue 
The gitpod.yml file will contain information such as the Docker image to use for the development environment, any required environment variables, and any additional commands that should be run when the environment is launched. By providing this file, I hope to make it easier for developers to contribute to the project and streamline the development process.
can you please assign this issue to me...

**Comment by GautamR-Samagra** [comment]
Taken over here -  https://github.com/Samagra-Development/ai-tools/issues/153
