### ISSUE TITLE
Add CI using GitHub Workflows

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#6]
The CI should

- [ ] Installation
- [ ] Run the integration test suite
- [ ] Run the Unit tests suite

When

- [ ] On a PR
- [ ] Before merging

Outputs

- [ ] Badges on coverage

Karun

**Comment by infinite8loop** [comment]
Hello,
I had a perusal on the package.json and the services in the directory "app" and understood that ts and NestJS being used, could you let me the process/commands for building and testing the services so that I can prepare a pipeline yaml for the same?

**Comment by singhalkarun** [comment]
@GautamR-Samagra Can we have a /health endpoint for each model that internally inferences/tests the model and returns {status: ok} if it is working fine.
