### ISSUE TITLE
Setup guardrails and https://rebuff.ai/ for LLM's input/output validation

### ISSUE THREAD

**Issue by singhalkarun** [Samagra-Development/ai-tools#84]
Setup 
1. guardrails.ai 
2. and https://rebuff.ai/

**Comment by goyalpramod** [comment]
Heya there @singhalkarun This seems really interesting and I would love to work on it. Can you please assign it to me? I will start exploring it and share my timeline and methodology in a while.

**Comment by ChakshuGautam** [comment]
Please go ahead!!!

**Comment by goyalpramod** [comment]
@ChakshuGautam Thank you, I will start working on it. As it still seems new to me, I may pester you for some guidance. Will it be alright if I text you over Discord?

**Comment by goyalpramod** [comment]
#98 Kindly check the following pull request and let me know if it meets the requirements. Please mention if anything needs to be changed and I shall do it.
