### ISSUE TITLE
Master Ticket for New Models

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#85]
- [ ] Farming Classifier
	- BERT > BART (Add references)
	- [ ] BERT
- [ ] Dictionary Augmented Translation
- [ ] Is Coref Required (Smaller model - 20MB)
- [ ] Is Coref Correct
- [ ] Training coref on farming data 
- [ ] Check Relevancy
- [ ] Answering Based on Content (Descriptive Answers)
	- BART > BERT (Add references)
	- [ ] BART
- [ ] Odia Speech to Text
	- [ ] Fairseq
	- [ ] NeMo

## Outcome
- [ ] Trained Model
- [ ] Integrating it with Ai Tools
- [ ] Putting the weights and trained model on Huggingface
- [ ] Publishing Results as a Blog/Arxiv
- [ ] Training Data and Testing Data as part of GitHub

**Comment by GautamR-Samagra** [comment]
Timelines : 

- [ ] Farming Classifier
	- [ ] BERT ( 19-05-2023) 
- [ ] Dictionary Augmented Translation 
    - [ ] Simple find and replace based on input/output (19-05-2023) 
- [ ] Is Coref Required (Smaller model - 20MB)  (19-05-2023) 
- [ ] Is Coref Correct (25-02-2023) *(Not sure we should be building a model for this, will explore based on coref efficiency)*
- [ ] Check Relevancy (23-05-2023)
- [ ] Answering Based on Content (Descriptive Answers)
	- [ ] BART (25-05-2023) 
- [ ] Odia Speech to Text
	- [ ] *Fairseq* 
	- [ ] NeMo (22-05-2023) Script for training and fine-tuning 
- [ ] *Training coref on farming data*

**Comment by ChakshuGautam** [comment]
1. Dict Augmented Translation
 - [ ] Push whatever is done as a PR
 - [ ] Create a ticket for GPT Based Dict Creation - Document Process
 - [ ] Tag everyone interested in this and share it on discord to literature review on this
2. Farming Classifier
 - [ ] Create a new repo for this and push everything there.
 - [ ] Push to huggingface
 - [ ] AI Tools to use huggingface
3. Is Coref Required
 - [ ] Create a ticket for the current solution and paste the code entirely.
 - [ ] Ask for contributors to add this to ai-tools
 - [ ] Ask for contributors - And do literature review as well
4. Is Coref Correct
 - [ ] Create a ticket

**Comment by ChakshuGautam** [comment]
- [ ] Nemo - Setting up notebook on Azure (Check for parallel multiple GPUs)

**Comment by GautamR-Samagra** [comment]
Completed and incomplet work carried onto other tickets
