### ISSUE TITLE
Add OpenAPI Spec

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#9]
- `POST` /useCase/model
- `POST` /health
- `POST` /embeddings/model

Samvit

**Comment by sanjay-aurigait** [comment]
@ChakshuGautam can you give more understanding regarding this ticket

**Comment by J-e-e-t** [comment]
@ChakshuGautam Can you please assign this task to me?

**Comment by Dhruv88** [comment]
Can I have this issue if it is still available?
