### ISSUE TITLE
Enable ASR using Fairseq

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/ai-tools#95]
Fariseq launched this yesterday and we would like to include all of them in our toolchain.

- [ ] ASR - input would be the language and a link to wav file that needs to be downloaded and inferred. Output is text string;

**Comment by GautamR-Samagra** [comment]
We need to use [this](https://github.com/facebookresearch/fairseq/tree/main/examples/mms) link and the models used in it. You can use the smallest model (with ~120 languages). Inference API code also seems available there
They need to create a sheet similar to [this](https://docs.google.com/spreadsheets/d/1Asd_F52wGRuibI0-zfTKycwzc0ltVNe7GoLPpfxlNaY/edit#gid=0). You only need to create the column which shows the linked audio and the transcripts.  You need not generate the other columns.  The accuracy etc will be calculated later in another ticket.  


The linked audio files have been zipped [here](https://drive.google.com/file/d/1CBFUCzbjgQYcgp3a1rZi4-1XfbCkzS15/view?usp=sharing) in into folder so that you can easy pass the files into the inference api above. We'll need to convert the mp3 to .wav files. you can do that also in python

**Comment by GautamR-Samagra** [comment]
Can use the collab [code] (https://colab.research.google.com/drive/1H0tJr5CZObOsnxpCvOgt2WX28uxAeHYc?usp=sharing) to calculate WER

**Comment by ItshMoh** [comment]
i was working on this issue. I run the code as given in the link . everything works fine . at the last step i was getting an error like this.
Traceback (most recent call last):
  File "/content/fairseq/examples/mms/asr/infer/mms_infer.py", line 63, in <module>
    process(args)
  File "/content/fairseq/examples/mms/asr/infer/mms_infer.py", line 53, in process
    with open(tmpdir/"hypo.word") as fr:
FileNotFoundError: [Errno 2] No such file or directory: '/content/temp_dir/tmp92gmo_hb/hypo.word'

can you suggest me some step to resolve the issue
i was using the google colab code.

**Comment by ChakshuGautam** [comment]
Hey can you raise this on the Fairseq github?

**Comment by ItshMoh** [comment]
I have gone through the file which is supposed to have error [link](https://github.com/facebookresearch/fairseq/blob/main/examples/mms/asr/infer/mms_infer.py)
In this code the error starts from line 53. I searched for some solutions, but i couldn't find something useful. 
This is my code [link](https://colab.research.google.com/drive/1alIozvkyihmHI35_X2gdQ-LB4pseVksB?usp=sharing) .

**Comment by rishav-eulb** [comment]
@ChakshuGautam  @GautamR-Samagra  Among 50, I'm done with 30. Link :-https://docs.google.com/spreadsheets/d/10kuyGJUBXaBtaFH0WiYRbyKDsWmr9VvyXSwtHI_JW7E/edit?usp=sharing. I'll be done with the rest till tomorrow

**Comment by rishav-eulb** [comment]
Some of the wav file is not running in google colab because of lack of memory, we can either use colab pro, or system with high specifications

**Comment by rishav-eulb** [comment]
@GautamR-Samagra @ChakshuGautam, should I also translate the ones, whose actual output is not given?

**Comment by GautamR-Samagra** [comment]
No need, only the ones with the given output for now.

**Comment by ChakshuGautam** [comment]
Hey @rishav-eulb can you publish the BLEU score as well once done?

**Comment by ItshMoh** [comment]
@ChakshuGautam @Cyber-Machine 
The hypo.word file is not found can be resolved with these changes in code
 
In infer.config.yml file a new top level key should be formed . it is for the error CUDA not found.
`common:
   cpu: true`

In infer.py file we have to do this
`out = subprocess.run(cmd, check=True, shell=True, stdout=subprocess.DEVNULL,)
print(out)`

**Comment by ChakshuGautam** [comment]
Is it working fine now?

**Comment by ItshMoh** [comment]
i tried this and i am able to run .  i found some of the wav to text file 
 write like this
for infer.config.yml
common:
   cpu: true

for infer.py file 
out = subprocess.run(cmd, check=True, shell=True, stdout=subprocess.DEVNULL,) 
print(out)

**Comment by ItshMoh** [comment]
> Is it working fine now?

yes it is working . I have converted some audio file to text file. some file was not converted due to crash of ram , they can be done by google pro.

**Comment by rishav-eulb** [comment]
> Hey @rishav-eulb can you publish the BLEU score as well once done?
> 
> Also can you share the code snippet you are using to do this?

Sure Sir

**Comment by rishav-eulb** [comment]
> No need, only the ones with the given output for now. Do share the notebook/codebase too where you have carried this out

Sure Sir

**Comment by rishav-eulb** [comment]
Sir here is the link of transcribe text :-https://docs.google.com/spreadsheets/d/10kuyGJUBXaBtaFH0WiYRbyKDsWmr9VvyXSwtHI_JW7E/edit?usp=sharing
Link to notebook :- 
https://colab.research.google.com/drive/19OmVk8Mc4nmpjTcPo0IG1sF-IjkFIsO8?usp=sharing

**Comment by rishav-eulb** [comment]
@GautamR-Samagra  @ChakshuGautam  can you cross check one. I have updated BLEU score

**Comment by GautamR-Samagra** [comment]
@rishav-eulb this works. Performance is better than our other models. Can you contribute your code to ai-tools as a PR. We'll integrate it to the whole repo.

**Comment by rishav-eulb** [comment]
Done!

**Comment by GautamR-Samagra** [comment]
Current state : 
- Performance better than conformer model with only issue being spelling mistakes 
- Bug in NVIDIA cuda installation that needs to be resolved - https://github.com/GautamR-Samagra/fairseq_gpu_deployment/issues/1
- ngram search to be developed as a part of dictionary augmented transformers C4GT project week 2 which will resolve the spelling mistakes issue over time

**Comment by rishav-eulb** [comment]
> Current state :
> 
> * Performance better than conformer model with only issue being spelling mistakes
> * Bug in NVIDIA cuda installation that needs to be resolved - [Docker unable to build image. GautamR-Samagra/fairseq_gpu_deployment#1](https://github.com/GautamR-Samagra/fairseq_gpu_deployment/issues/1)
> * ngram search to be developed as a part of dictionary augmented transformers C4GT project week 2 which will resolve the spelling mistakes issue

Regarding pointer 2. If you have installed docker properly on windows you might be able to create dockerfile using python as a base image, but while using nvidia_cuda as a base image, it's taking infinite time to execute.

**Comment by singhalkarun** [comment]
Closing this as implemented by internal team.
